apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s9xft9i91-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/s9xft9i91-dotnet-basic-gitops